"""add support for async in books

Revision ID: 10b00f066c0f
Revises: 7c4fd85ef28d
Create Date: 2021-10-15 17:19:53.694914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b00f066c0f'
down_revision = '7c4fd85ef28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
