"""fix whishlists

Revision ID: 34d74e1e4773
Revises: 32b0cac41019
Create Date: 2021-10-23 16:29:39.691010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d74e1e4773'
down_revision = '32b0cac41019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    op.create_table('wishlisted_books',
    sa.Column('wishlist_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], )
    )
    op.drop_table('whishlisted_books')
    op.drop_index('ix_whishlists_id', table_name='whishlists')
    op.drop_table('whishlists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whishlists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('whishlists_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='whishlists_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='whishlists_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_whishlists_id', 'whishlists', ['id'], unique=False)
    op.create_table('whishlisted_books',
    sa.Column('whishlist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='whishlisted_books_book_id_fkey'),
    sa.ForeignKeyConstraint(['whishlist_id'], ['whishlists.id'], name='whishlisted_books_whishlist_id_fkey')
    )
    op.drop_table('wishlisted_books')
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.drop_table('wishlists')
    # ### end Alembic commands ###
