"""test2

Revision ID: 3ed399eda4cb
Revises: 53a8f87bd6d8
Create Date: 2021-10-10 16:47:15.612386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed399eda4cb'
down_revision = '53a8f87bd6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_reviews_review_date'), 'reviews', ['review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_review_date'), table_name='reviews')
    op.drop_column('reviews', 'review_date')
    # ### end Alembic commands ###
